sudo: required

language: go

go:
  - "1.13"

services:
  - docker

branches:
  only:
    - master

git:
  submodules: false

script:
  - export REPO=edintc/checq-api
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f api/Dockerfile -t $REPO:$TAG api/.
  - docker tag $REPO:$TAG $REPO:travis-$TRAVIS_BUILD_NUMBER

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin ;
      docker push $REPO ;
    fi