version: "3.7"

networks:
  web:
    external: true
  internal:
    external: false

services:
  traefik:
    image: traefik:1.7
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./.docker/traefik.toml:/traefik.toml"
      - "./.docker/acme.json:/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    labels:
      - traefik.frontend.rule=Host:traefik.checq.intercube.io
      - traefik.port=8080

  api:
    image: edintc/checq-api:latest
    restart: always
    volumes:
      - ./api:/go/src/github.com/EdinTC/Checq/api
    ports:
      - "1337:1337"
    networks:
      - internal
      - web
    labels:
      - traefik.backend=API
      - traefik.frontend.rule=Host:api.checq.intercube.io
      - traefik.docker.network=web
      - traefik.port=1337

  frontend:
    image: edintc/checq-frontend:latest
    restart: always
    volumes:
      - ./frontend/public:/frontend/public
    networks:
      - internal
      - web
    labels:
      - traefik.backend=Frontend
      - traefik.frontend.rule=Host:checq.intercube.io
      - traefik.docker.network=web
      - traefik.port=80
