version: '3.7'

services:
  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV} # TODO: Define this in 1 place
    volumes:
      - ./api:/go/src/github.com/edintc/checq/api
    ports:
      - "5000:8000"

  frontend: # TODO: Decide on what frontend to use
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV} # TODO: Define this in 1 place
    volumes:
      - #
    ports:
      - #