version: '3.7'

services:
  api:
    build:
      context: ./api
      args:
        app_env: ${APP_ENV} # TODO: Define this in 1 place
    volumes:
      - ./api:/go/src/github.com/EdinTC/Checq/api
    ports:
      - "5000:8080"

  frontend: # TODO: Decide on what frontend to use
    build:
      context: ./frontend
      args:
        app_env: ${APP_ENV} # TODO: Define this in 1 place
    volumes:
      - #
    ports:
      - #