name: Build and Publish images

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: A) Build the images
      run: |
        docker build -f frontend/Dockerfile -t $(cat DOCKERHUB_USER)/checq-frontend frontend/.
        docker build -f api/Dockerfile -t $(cat DOCKERHUB_USER)/checq-api api/.

    - name: B) Push docker images to registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username $(cat DOCKERHUB_USER) --password-stdin
        docker push $(cat DOCKERHUB_USER)/checq-frontend
        docker push $(cat DOCKERHUB_USER)/checq-api
