name: Build and Publish images

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: A) Define VARs
      run: |
        echo "edintc/checq-frontend:latest" > TAG_FRONTEND_LATEST
        echo "edintc/checq-api:latest" > TAG_API_LATEST

    - name: B) Display docker image tags
      run: |
        echo "Our 2 tags are:"
        #
        echo $(cat TAG_FRONTEND_LATEST)
        echo $(cat TAG_API_LATEST)

    - name: C) Build the images
      run: |
        docker build -f frontend/Dockerfile --tag $(cat TAG_FRONTEND_LATEST) frontend/.
        docker build -f api/Dockerfile --tag $(cat TAG_API_LATEST) api/.


    - name: D) Push docker images to registry
      run: |
        docker login -u ${{ DOCKER_USERNAME }} -p ${{ DOCKER_PASSWORD }}
        docker push $(cat TAG_FRONTEND_LATEST)
        docker push $(cat TAG_API_LATEST)
